### ISSUE TITLE
Hello darkdarcool

### ISSUE THREAD

**Issue by CodingRedpanda** [darkdarcool/DSMD-Interpreter#1]
The source code (`main.py`) is interpreted so you can't call DSMD 'compiled', because the base source code for it is not compiled, so probably change the name from **DSMD-Compiler** to **DSMD-interpreter**.

Very cool btw

**Comment by darkdarcool** [comment]
ill probs do that. (i have to switch a couple links i put then). You can also fork the project and get it on replit and then edit README.dsmd so you can try it out!

**Comment by CodingRedpanda** [comment]
Repl.it and Replit.com are both blocked by my school (for some idiotic reason), so I'll probably do it on my pc.

**Comment by CodingRedpanda** [comment]
also i like ur new pfp

**Comment by darkdarcool** [comment]
thanks. I think it reflects my personality. It is a gif but git is only showing one frame. Here is the actual gif(if it loads as a gif_:
![200](https://user-images.githubusercontent.com/66882633/116557133-0287d200-a8b3-11eb-8211-e3a25d554523.gif)

**Comment by CodingRedpanda** [comment]
lol, well, i did image search and found the gif [here](https://steamuserimages-a.akamaihd.net/ugc/911293473580328863/DCB12F76423E5226064ABC302B326C2F527A42DF/). Also ~~im making a secret project~~ i used **gitpod** to execute the [code](https://gitpod.io/#/https://github.com/darkdarcool/DSMD-Interpreter/).

**Comment by darkdarcool** [comment]
lol vs code clone

**Comment by CodingRedpanda** [comment]
ikr

**Comment by darkdarcool** [comment]
anyway kewl. Also why did you tell me your making a secret project?

**Comment by darkdarcool** [comment]
It kinda spoils the secret

**Comment by CodingRedpanda** [comment]
its a shell kinda thing

**Comment by CodingRedpanda** [comment]
but better

**Comment by darkdarcool** [comment]
don't tell me its [this](https://github.com/CodingRedpanda/Notepad)

**Comment by darkdarcool** [comment]
oh, ok

**Comment by CodingRedpanda** [comment]
no, no lol

**Comment by CodingRedpanda** [comment]
im adding all kinds of things

**Comment by darkdarcool** [comment]
oh ok, can I see it(you don't have to let me see it, but it sounds cool)

**Comment by CodingRedpanda** [comment]
oh, its a private github project

**Comment by darkdarcool** [comment]
you can still invite me to it

**Comment by darkdarcool** [comment]
in settings. in collaborators or something

**Comment by CodingRedpanda** [comment]
the progress is on ~~vscode clone~~ gitpod rn

**Comment by CodingRedpanda** [comment]
giv me a moment ill inv u

**Comment by darkdarcool** [comment]
oh ok. Also its on manage access tab

**Comment by CodingRedpanda** [comment]
its called Axolotl bcause y not

**Comment by darkdarcool** [comment]
okkkkkie

**Comment by CodingRedpanda** [comment]
*Aks-Suh-Lah-Tol* is how u pronouce it

**Comment by darkdarcool** [comment]
okkkkkkkay(still can't pronounce it)

**Comment by CodingRedpanda** [comment]
Axolotl: 
![Axolotl](https://user-images.githubusercontent.com/64909897/116581210-172f8e80-a8e2-11eb-9b27-402672ce7766.png)

**Comment by CodingRedpanda** [comment]
wat languages should i implement it in?

**Comment by darkdarcool** [comment]
python. ruby. Bash(bash covers like 90 percent of Langs). node. deno. typescript

**Comment by darkdarcool** [comment]
hey, you wanna help me make my readme?(in replit). I could teach you DSMD

**Comment by CodingRedpanda** [comment]
> bash covers like 90 percent of Langs

so tru
> hey you wanna help me make my readme

ig but replit is blocked for me

**Comment by darkdarcool** [comment]
hm. welllllllllllllllllllll. then idk

**Comment by CodingRedpanda** [comment]
it categorized as security.proxy, whatever that means

**Comment by darkdarcool** [comment]
welp idk.

**Comment by CodingRedpanda** [comment]
if u send me inv on replit ill go on it later prbly

**Comment by CodingRedpanda** [comment]
gtg, btw i need a new username for replit/github so if u have any good ones comment in this and ill check later

**Comment by darkdarcool** [comment]
okiiiie.

**Comment by darkdarcool** [comment]
anyway, ttyl

**Comment by darkdarcool** [comment]
bai

**Comment by darkdarcool** [comment]
@CodingRedpanda, it's out! The first version of DSMD! Please do: 
```
pip install DSMD
```
Then in main.py:
```
from DSMD import parse
parse("my_md_file.md")
```
Then you can see DSMD in action!

**Comment by CodingRedpanda** [comment]
kk will do, good job

**Comment by darkdarcool** [comment]
thanks!

**Comment by CodingRedpanda** [comment]
i have access to replit so
> hey, you wanna help me make my readme?(in replit). I could teach you DSMD

sure

**Comment by darkdarcool** [comment]
@CodingRedpanda, I can't do it today because I have school, but maybe tomorrow? If you can wait, go [here](https://github.com/whippingdot/Language-Tutorials/tree/main/DSMD) for the start of a tutorial.

**Comment by CodingRedpanda** [comment]
Ok, thx

**Comment by darkdarcool** [comment]
Cool
